# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TDDAndRefactor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TDDAndRefactor

  target 'TDDAndRefactorTests' do
    inherit! :search_paths
    pod 'Mockingbird-Swift', '~> 2.0'
    # Pods for testing
  end

  target 'TDDAndRefactorUITests' do
    # Pods for testing
  end

end
