# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '91TDDAndRefactor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Mockingbird-Swift', '~> 2.0'
  # Pods for 91TDDAndRefactor

  target '91TDDAndRefactorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '91TDDAndRefactorUITests' do
    # Pods for testing
  end

end
